# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'MapView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapView
  pod 'FMDB', '2.7.2'
  pod 'GRMustache', '7.3.2'
  pod 'SMCalloutView', '2.1.5'
end
